"""Inventory QR images generated by QRGuard without publishing the image trees."""

from __future__ import annotations

import hashlib
import json
from collections import Counter
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "ml_training/datasets/generated_qr_codes/registry.json"


@dataclass(frozen=True)
class GeneratedSet:
    dataset_id: str
    relative_root: str
    pattern: str
    intended_use: str
    exposure_states: tuple[str, ...]
    generator: str
    source_manifest: str | None = None
    group_from_path: Callable[[Path], str] | None = None


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _tree_record(spec: GeneratedSet) -> dict[str, object]:
    root = ROOT / spec.relative_root
    files = sorted(path for path in root.glob(spec.pattern) if path.is_file())
    tree = hashlib.sha256()
    total_bytes = 0
    groups: Counter[str] = Counter()

    for path in files:
        relative = path.relative_to(root)
        size = path.stat().st_size
        file_hash = _sha256(path)
        tree.update(relative.as_posix().encode("utf-8"))
        tree.update(b"\0")
        tree.update(str(size).encode("ascii"))
        tree.update(b"\0")
        tree.update(file_hash.encode("ascii"))
        tree.update(b"\n")
        total_bytes += size
        if spec.group_from_path is not None:
            groups[spec.group_from_path(relative)] += 1

    manifest = ROOT / spec.source_manifest if spec.source_manifest else None
    return {
        "dataset_id": spec.dataset_id,
        "path": spec.relative_root,
        "file_pattern": spec.pattern,
        "file_count": len(files),
        "total_bytes": total_bytes,
        "tree_sha256": tree.hexdigest(),
        "groups": dict(sorted(groups.items())),
        "intended_use": spec.intended_use,
        "exposure_states": list(spec.exposure_states),
        "generator": spec.generator,
        "source_manifest": spec.source_manifest,
        "source_manifest_sha256": (
            _sha256(manifest) if manifest is not None and manifest.is_file() else None
        ),
    }


def _campaign_group(path: Path) -> str:
    case_id = path.parts[0]
    prefix, condition, *_ = case_id.split("-")
    label = {"cln": "clean", "adv": "adversarial", "tmp": "tampered"}.get(
        prefix, "other"
    )
    return f"{label}/{condition}"


SETS = (
    GeneratedSet(
        dataset_id="legacy-benign-malicious-5000",
        relative_root="data/structural/qr_images",
        pattern="**/*.png",
        intended_use="legacy compatibility only; not current Structural training",
        exposure_states=("legacy_not_current",),
        generator="historical generator not retained as a current recipe",
        group_from_path=lambda path: path.parts[0],
    ),
    GeneratedSet(
        dataset_id="structural-2026.03-r01-procedural-images",
        relative_root=(
            "ml_training/datasets/structural/processed/structural-2026.03-r01/images"
        ),
        pattern="**/*.png",
        intended_use="current Structural run; split membership is manifest-governed",
        exposure_states=("training", "validation", "locked_test"),
        generator="ml_training/structural/src/structural_recipes.py",
        source_manifest=(
            "ml_training/datasets/structural/processed/"
            "structural-2026.03-r01/manifest.csv"
        ),
        group_from_path=lambda path: path.parts[0],
    ),
    GeneratedSet(
        dataset_id="structural-v3-real-2026.03-r01-capture-references",
        relative_root="data/capture_pilot/structural-v3-real-2026.03-r01",
        pattern="**/*-gallery-reference.png",
        intended_use="display/print references for exact-app real capture",
        exposure_states=("capture_reference",),
        generator="ml_training/structural/src/capture_campaign.py",
        group_from_path=_campaign_group,
    ),
    GeneratedSet(
        dataset_id="structural-2026.03-r01-prepared-gallery-references",
        relative_root=(
            "data/prepared_gallery_references/structural-2026.03-r01/images"
        ),
        pattern="**/*.png",
        intended_use="train/validation Gallery reference import; locked test excluded",
        exposure_states=("training", "validation"),
        generator="scripts/import_prepared_gallery_references.py",
        source_manifest=(
            "data/prepared_gallery_references/structural-2026.03-r01/manifest.csv"
        ),
        group_from_path=lambda path: path.parts[0],
    ),
    GeneratedSet(
        dataset_id="qr-codes-demo-2026-08-31-r01-r05",
        relative_root="ml_training/datasets/qr_codes_demo",
        pattern="**/*.png",
        intended_use=(
            "post-training supervisor demonstration; never training or independent "
            "performance evidence"
        ),
        exposure_states=("demo_only", "post_training_exposed"),
        generator="scripts/build_qr_codes_demo.py",
        source_manifest="ml_training/datasets/qr_codes_demo/MANIFEST.json",
        group_from_path=lambda path: path.parts[0],
    ),
    GeneratedSet(
        dataset_id="legacy-api-test-qrs",
        relative_root="data/test_qrs",
        pattern="*.png",
        intended_use="superseded manual API tests; not current demo evidence",
        exposure_states=("legacy_not_current",),
        generator="scripts/make_test_qrs.py",
    ),
    GeneratedSet(
        dataset_id="legacy-gallery-test-cards",
        relative_root="data/app_gallery/QRGuard_Test_QRs",
        pattern="*.png",
        intended_use="superseded Gallery cards; not current demo evidence",
        exposure_states=("legacy_not_current",),
        generator="scripts/make_gallery_qrs.py",
    ),
)


def main() -> None:
    payload = {
        "schema_version": 1,
        "inventory_date": "2026-08-31",
        "hash_contract": "sha256(path\\0size\\0file_sha256\\n) over sorted paths",
        "datasets": [_tree_record(spec) for spec in SETS],
    }
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)} with {len(SETS)} generated datasets")


if __name__ == "__main__":
    main()
